# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intern < Formula
  desc "Proxy and profiler for Anthropic Claude API sessions"
  homepage "https://github.com/abhishekjha17/intern"
  version "0.1.3"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.3/intern_0.1.3_darwin_amd64.tar.gz"
      sha256 "46f7870e3910490c663312047f90d20faf4ddb307a818dfd55dc32bc708fc18b"

      define_method(:install) do
        bin.install "intern"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.3/intern_0.1.3_darwin_arm64.tar.gz"
      sha256 "071810178ca64eb01b007460e41a3320732a2f420f50d2147f15cc8658a31d8e"

      define_method(:install) do
        bin.install "intern"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.3/intern_0.1.3_linux_amd64.tar.gz"
      sha256 "612e273f877c68415b2ca2c702d698a9a2823bf12b4a21c6d56c7c1dd61c654c"
      define_method(:install) do
        bin.install "intern"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.3/intern_0.1.3_linux_arm64.tar.gz"
      sha256 "b23ef428738572afc02b648cb5148b4f35cb49f1aa613c98624c0ada2d5863c4"
      define_method(:install) do
        bin.install "intern"
      end
    end
  end

  def post_install
    (var/"log/intern").mkpath
  end

  def caveats
    <<~EOS
      To start intern as a background service:
        brew services start intern

      The proxy listens on http://localhost:11411 by default.
      Point your Claude client's API base URL there.

      Traces are written to:
        #{var}/log/intern/traces.jsonl

      To analyze your traces:
        intern profile #{var}/log/intern/traces.jsonl
    EOS
  end

  service do
    run [opt_bin/"intern", "proxy", "--port", "11411", "--trace", var/"log/intern/traces.jsonl"]
    keep_alive true
    log_path var/"log/intern/intern.log"
    error_log_path var/"log/intern/intern.log"
  end
end
