# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intern < Formula
  desc "Proxy and profiler for Anthropic Claude API sessions"
  homepage "https://github.com/abhishekjha17/intern"
  version "0.1.2"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.2/intern_0.1.2_darwin_amd64.tar.gz"
      sha256 "d45438fec5c9949b545725f684ecc172839af57ddb8c84fb0ba64056dd1c8768"

      define_method(:install) do
        bin.install "intern"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.2/intern_0.1.2_darwin_arm64.tar.gz"
      sha256 "bb380d0d9b06c40ec99648aca1c5ca90051b428d994510880d9c642ae25e81fb"

      define_method(:install) do
        bin.install "intern"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.2/intern_0.1.2_linux_amd64.tar.gz"
      sha256 "5635c304c6b9551495cc6b86918b62c0ec9f990e4bd3e1c770aee22ec6a9cf41"
      define_method(:install) do
        bin.install "intern"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.2/intern_0.1.2_linux_arm64.tar.gz"
      sha256 "a60e647701c55114b802d40c54d0684790c96006055bef24ea6e761bd4ed93e4"
      define_method(:install) do
        bin.install "intern"
      end
    end
  end

  def post_install
    (var/"log/intern").mkpath
  end

  def caveats
    <<~EOS
      To start intern as a background service:
        brew services start intern

      The proxy listens on http://localhost:11411 by default.
      Point your Claude client's API base URL there.

      Traces are written to:
        #{var}/log/intern/traces.jsonl

      To analyze your traces:
        intern profile #{var}/log/intern/traces.jsonl
    EOS
  end

  service do
    run [opt_bin/"intern", "proxy", "--port", "11411", "--trace", var/"log/intern/traces.jsonl"]
    keep_alive true
    log_path var/"log/intern/intern.log"
    error_log_path var/"log/intern/intern.log"
  end
end
