# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intern < Formula
  desc "Proxy and profiler for Anthropic Claude API sessions"
  homepage "https://github.com/abhishekjha17/intern"
  version "0.1.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.0/intern_0.1.0_darwin_amd64.tar.gz"
      sha256 "f7f9626f5c017d5118576cedb3fb30764fc08f115e13d3ae1f0f337534c76d7f"

      define_method(:install) do
        bin.install "intern"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.0/intern_0.1.0_darwin_arm64.tar.gz"
      sha256 "0d2eb617a9d0fbb71b695d1c1439059118612fa9c88a2eefb847f3b9bea8fdaf"

      define_method(:install) do
        bin.install "intern"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.0/intern_0.1.0_linux_amd64.tar.gz"
      sha256 "0bdb756800f3be011fe7ca4f5d6505b2924a73281fb10afc5f3e9eb2d3a5ebf3"
      define_method(:install) do
        bin.install "intern"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhishekjha17/intern/releases/download/v0.1.0/intern_0.1.0_linux_arm64.tar.gz"
      sha256 "f4b69a7ed32df89bbba589feb47e841433626468666e0eca4b9af89ded9c74b5"
      define_method(:install) do
        bin.install "intern"
      end
    end
  end

  def post_install
    (var/"log/intern").mkpath
  end

  def caveats
    <<~EOS
      To start intern as a background service:
        brew services start intern

      The proxy listens on http://localhost:11411 by default.
      Point your Claude client's API base URL there.

      Traces are written to:
        #{var}/log/intern/traces.jsonl

      To analyze your traces:
        intern profile #{var}/log/intern/traces.jsonl
    EOS
  end

  service do
    run [opt_bin/"intern", "proxy", "--port", "11411", "--trace", var/"log/intern/traces.jsonl"]
    keep_alive true
    log_path var/"log/intern/intern.log"
    error_log_path var/"log/intern/intern.log"
  end
end
